version: '3.8'
services:
  fasol:
    build: 
      context: .    # Build context is the current directory
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Map host port to container port
    volumes:
      - .:/usr/src/app  # Mount the current directory into the container
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=mysqldb
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=nopass
      - DB_DATABASE=fasol
    networks:
      - backend-network
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=nopass
      - MYSQL_DATABASE=fasol
    volumes:
      - data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3308:3306"
    networks:
      - backend-network
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    depends_on:
      - fasol

networks:
  backend-network:
    driver: bridge

volumes:
  data:
    driver: local